---
#auther: han
- hosts: docker-manager-first
  become: yes
  vars:
    swarm_advertise_addr: "{{ ansible_default_ipv4.address }}"
    docker_swarm_port: 2377
  tasks:
    - include_tasks: tasks/docker_swarm_init.yml

- hosts: docker-works
  become: yes
  tasks:
    - include_tasks: tasks/join_worker_node.yml
