---
# author: hanxiong

- name: configure | Setup nginx.conf.
  template:
    dest: "{{ nginx_conf_file_path }}"
    src: nginx.conf.j2
    mode: 0644
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
  notify: Reload nginx.

#- name: configure vhost marketapi.conf.
#  template:
#    dest: "{{ nginx_conf_path }}/vhost/marketapi.conf"
#    src: marketapi.conf.j2
#    mode: 0644
#    owner: "{{ nginx_user }}"
#    group: "{{ nginx_group }}"

#- name: configure vhost marketws.conf.
#  template:
#    dest: "{{ nginx_conf_path }}/vhost/marketws.conf"
#    src: marketws.conf.j2
#    mode: 0644
#    owner: "{{ nginx_user }}"
#    group: "{{ nginx_group }}"

#- name: configure roles deny.conf.j2.
#  template:
#    dest: "{{ nginx_conf_path }}/roles/deny.conf"
#    src: deny.conf.j2
#    mode: 0644
#    owner: "{{ nginx_user }}"
#    group: "{{ nginx_group }}"

#- name: configure vhost ssl.conf.j2.
#  template:
#    dest: "{{ nginx_conf_path }}/vhost/ssl.conf"
#    src: ssl.conf.j2
#    mode: 0644
#    owner: "{{ nginx_user }}"
#    group: "{{ nginx_group }}"

- name: configure | Setup nginx.sh file.
  template:
    dest: "/etc/rc.d/init.d/nginx"
    mode: 0755
    src: nginx.sh.j2

- name: configure | Add nginx services.
  shell: "chkconfig --add nginx && chkconfig nginx on"
  
- name: configure | Ensure nginx is running for centos6.
  service: "name=nginx state=started enabled=yes"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  
- name: configure | Ensure nginx is running for centos7.
  systemd: "name=nginx state=started enabled=yes"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
