---
# author: hanxiong
- name: create | /data/apps/nginx/geoip dir to agent.
  file:
    path: "/data/apps/nginx/geoip"
    state: directory

- name: install | Copy {{ libmaxminddb_name }} file to agent.
  unarchive:
    src: "{{ software_files_path }}/{{ libmaxminddb_name }}"
    dest: "{{ party_modules_files_path }}"
    creates: "{{ party_modules_files_path }}/libmaxminddb-1.3.2"

- name: install | Copy libmaxminddb file to agent.
  unarchive:
    src: "{{ software_files_path }}/{{ maxmind_city_name }}"
    dest: "/data/apps/nginx/geoip"

- name: install | Build an install libmaxminddb-1.3.2.
  shell: "{{ item }}"
  with_items:
    - "{{ libmaxminddb_configure_command }}"
    - make && make install
  args:
    chdir: "{{ party_modules_files_path }}/libmaxminddb-1.3.2"

- name: echo ldconfig_name to /etc/ld.so.conf.d/local.conf
  raw: "echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf;ldconfig"
