---
# author: hanxiong
- name: install | Check if nginx local file is already configured.
  stat: path={{ lua_nginx_file_path }}
  connection: local
  register: lua_nginx_file_result

- name: install | Download {{ lua_nginx_file_url }} file.
  get_url: url={{ lua_nginx_file_url }} dest={{ software_files_path }} validate_certs=false
  connection: local
  when: not lua_nginx_file_result.stat.exists

- name: install | create {{ party_modules_files_path }} path
  file: path={{ party_modules_files_path }} state=directory

- name: install | Copy lua-nginx-module-0.10.14rc4.tar.gz file to agent.
  unarchive:
    src: "{{ software_files_path }}/{{ lua_nginx_file_name }}"
    dest: "/data/apps/nginx/party_modules"
    creates: "{{ party_modules_files_path }}/lua-nginx-module-0.10.14rc4"