---
# author: hanxiong
- name: install | Check if ngx_cache_purge local file is already configured.
  stat: path={{ pure_nginx_file_path }}
  connection: local
  register: lua21_file_result

- name: install | Download {{ pureFileUrl }} file.
  get_url: url={{ pureFileUrl }} dest={{ software_files_path }} validate_certs=false
  connection: local
  when: not lua21_file_result.stat.exists

- name: install | create {{ party_modules_files_path }} path
  file: path={{ party_modules_files_path }} state=directory

- name: install | Copy {{ purefilename }} file to agent.
  unarchive:
    src: "{{ software_files_path }}/{{ purefilename }}"
    dest: "{{ party_modules_files_path }}"
    creates: "{{ party_modules_files_path }}/ngx_cache_purge-2.3"
